### ISSUE TITLE
Blank nodes are not correctly serialized, preventing the store from restarting properly

### ISSUE THREAD

**Issue by rmeissn** [AKSW/QuitStore#212] opened 2018-12-10 13:38 UTC
Blank nodes are serialised in the .nt files like
```
<http://localhost/item/1> <http://tech4comp/eal/hasAnswerText> _:_:b1_b0 .
_:_:b1_b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "42" .
_:_:b1_b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:_:b1_b1 .
_:_:b1_b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "43" .
_:_:b1_b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:_:b1_b2 .
_:_:b1_b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "41" .
_:_:b1_b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil> .
```
Judging from the log of the quit store:
```
2018-12-10 13:24:15,561 - quit.modules.endpoint - DEBUG - Request method: POST
2018-12-10 13:24:15,565 - quit.conf.QuitConfiguration - DEBUG - Initializing configuration object.
2018-12-10 13:24:15,567 - quit.modules.endpoint - ERROR - Invalid line: '_:b1_b0 .'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/ntriples.py", line 140, in parse
    self.parseline()
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/ntriples.py", line 196, in parseline
    self.eat(r_tail)
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/ntriples.py", line 210, in eat
    raise ParseError("Failed to eat %s at %s" % (pattern.pattern, self.line))
rdflib.plugins.parsers.ntriples.ParseError: Failed to eat [ \t]*\.[ \t]*(#.*)? at _:b1_b0 .
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./quit/web/modules/endpoint.py", line 93, in sparql
    graph, commitid = quit.instance(branch_or_ref)
  File "./quit/core.py", line 192, in instance
    (f, context) = self.getFileReferenceAndContext(blob, commit)
  File "./quit/core.py", line 411, in getFileReferenceAndContext
    graph.parse(data=content, format='nt')
  File "/usr/local/lib/python3.7/site-packages/rdflib/graph.py", line 1043, in parse
    parser.parse(source, self, **args)
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/nt.py", line 26, in parse
    parser.parse(f)
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/ntriples.py", line 142, in parse
    raise ParseError("Invalid line: %r" % self.line)
rdflib.plugins.parsers.ntriples.ParseError: Invalid line: '_:b1_b0 .'
```
I guess that `_:_:XYZ` is not parseable. The actual query (logged as of the commit) looked like:
```
Query: "INSERT DATA {
      GRAPH <http://localhost:3000/data> {
        <http://localhost/item/1> <http://purl.org/dc/terms/title> \"Test Question\".
        <http://localhost/item/1> <http://tech4comp/eal/context> \"This is a test setting\".
        <http://localhost/item/1> <http://tech4comp/eal/difficulty> \"9.6E0\"^^<http://www.w3.org/2001/XMLSchema#double>.
        <http://localhost/item/1> <http://tech4comp/eal/hasAnswerText> _:b1_b0.
        _:b1_b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> \"42\".
        _:b1_b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b1_b1.
        _:b1_b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> \"43\".
        _:b1_b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> _:b1_b2.
        _:b1_b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> \"41\".
        _:b1_b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil>.
      }
    }"
```
which is the correct blank node syntax. I guess blank nodes are somehow wrongly serialised to the .nt file. The actual error occurs as soon as the store is restarted, trying to read the wrongly serialized files.

**Comment by white-gecko** [comment] 2018-12-10 14:31
This is caused by: https://github.com/RDFLib/rdflib/pull/886

**Comment by white-gecko** [comment] 2018-12-14 17:16
Fixed by #214.
You can use the 2018-12-14 release from docker hub.

**Comment by rmeissn** [comment] 2018-12-18 09:21
I'm now using the docker hub image you specified above. Unfortunately it won't execute queries after a container restart (after reboot of the host) an produces the following log messages:
```
2018-12-18 09:13:09,206 - quit.modules.endpoint - DEBUG - Request method: POST
2018-12-18 09:13:09,259 - quit.conf.QuitConfiguration - DEBUG - Initializing configuration object.
2018-12-18 09:13:09,288 - quit.modules.endpoint - ERROR - Invalid line: '_b0 .'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/ntriples.py", line 154, in parse
    self.parseline()
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/ntriples.py", line 204, in parseline
    self.eat(r_tail)
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/ntriples.py", line 218, in eat
    raise ParseError("Failed to eat %s at %s" % (pattern.pattern, self.line))
rdflib.plugins.parsers.ntriples.ParseError: Failed to eat [ \t]*\.[ \t]*(#.*)? at _b0 .
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./quit/web/modules/endpoint.py", line 93, in sparql
    graph, commitid = quit.instance(branch_or_ref)
  File "./quit/core.py", line 192, in instance
    (f, context) = self.getFileReferenceAndContext(blob, commit)
  File "./quit/core.py", line 411, in getFileReferenceAndContext
    graph.parse(data=content, format='nt')
  File "/usr/local/lib/python3.7/site-packages/rdflib/graph.py", line 1030, in parse
    parser.parse(source, self, **args)
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/nt.py", line 26, in parse
    parser.parse(f)
  File "/usr/local/lib/python3.7/site-packages/rdflib/plugins/parsers/ntriples.py", line 156, in parse
    raise ParseError("Invalid line: %r" % self.line)
rdflib.plugins.parsers.ntriples.ParseError: Invalid line: '_b0 .'
[pid: 8|app: 0|req: 22/22] 172.17.0.1 () {46 vars in 1138 bytes} [Tue Dec 18 09:13:09 2018] POST /sparql => generated 29 bytes in 91 msecs (HTTP/1.1 400) 3 headers in 120 bytes (1 switches on core 0)

```
Nevertheless, the serialisation of blank nodes in the .nt files looks correct now:
```
...
_:b0_b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> "42" .
...
```

**Comment by white-gecko** [comment] 2018-12-18 09:34
Did you create the repository with the new container or did you add data with an old container before?

**Comment by rmeissn** [comment] 2018-12-18 09:38
I deleted the container and the used volume and recreated everything from scratch.

**Comment by white-gecko** [comment] 2018-12-18 11:17
What was the query that inserted this blank node? Is it the same as in the originial issue? If so, than this is a new issue. Please open a new issue.

**Closed by white-gecko** 2018-12-18 11:17 UTC
Labels: Blocked Upstream, bug

**Comment by rmeissn** [comment] 2018-12-18 12:30
Created issue #217 by request of @white-gecko
